import React, { useState, FunctionComponent, PropsWithChildren } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import { Navbar, Footer, Utterances } from "@Components/common";

const PageLayout: FunctionComponent<PropsWithChildren> = ({ children }) => {
  const router = useRouter();

  const slug = router.query.slug as string;

  const [isSearchEnabled, setIsSearchEnabled] = useState<boolean>(false);

  const clickSearchHandler = () => {
    setIsSearchEnabled(!isSearchEnabled);
  };

  const utterancesRepo = "seolleung2/dotorimook-nextjs-blog";

  return (
    <>
      <Head>
        <title>Dotorimook&#39;s DevLog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar isSearchEnabled={isSearchEnabled} onSearch={clickSearchHandler} />
      <section
        className={`${
          isSearchEnabled && "pt-[72px] sm:pt-[108px] lg:pt-36"
        } w-full`}
      >
        <div className="flex flex-col items-center border border-red-600">
          {children}
          {slug && <Utterances repo={utterancesRepo} path={slug} />}
        </div>
      </section>
      <Footer />
    </>
  );
};

export default PageLayout;
