import React from "react";
import Head from "next/head";
import Link from "next/link";
import { MagnifyingGlassIcon } from "@heroicons/react/24/solid";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Dotorimook&#39;s DevLog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="navigation border border-blue-500 w-full flex justify-between h-24 items-center p-6 lg:text-red-500">
        <div
          className="border border-red-500 text-5xl font-black font-Catamaran h-full flex items-center"
          id="main-logo"
        >
          <Link href="/">
            <h1>🌰DotoriLog</h1>
          </Link>
        </div>
        <ul className="flex border border-green-500 w-[420px] items-center justify-between font-Catamaran text-lg h-full">
          <li>Blogs</li>
          <li>Portfolio</li>
          <li>About</li>
          <li>
            <MagnifyingGlassIcon className="h-7 w-7 font-black" />
          </li>
        </ul>
      </nav>
      <section>
        <h1>DotoriJung 의 블로그 입니다 만세만세 만만세</h1>
      </section>
    </div>
  );
}
