import React, { useState } from "react";
import Head from "next/head";
import { Navbar, Footer } from "@Components/common";

interface IBaseLayoutProps {
  children: React.ReactNode;
}

const BaseLayout = ({ children }: IBaseLayoutProps) => {
  const [isSearchEnabled, setIsSearchEnabled] = useState<boolean>(false);

  const clickSearchHandler = () => {
    setIsSearchEnabled(!isSearchEnabled);
  };

  return (
    <>
      <Head>
        <title>Dotorimook&#39;s DevLog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar isSearchEnabled={isSearchEnabled} onSearch={clickSearchHandler} />
      <section
        className={`${
          isSearchEnabled && "pt-[72px] sm:pt-[108px] lg:pt-36"
        } w-full`}
      >
        {children}
      </section>
      <Footer />
    </>
  );
};

export default BaseLayout;
