import React, { useState, FunctionComponent, PropsWithChildren } from "react";
import Head from "next/head";
import { Navbar, Footer } from "@Components/common";

type Props = {
  pageTitle?: string;
};

const BaseLayout: FunctionComponent<PropsWithChildren<Props>> = ({
  children,
  pageTitle,
}) => {
  const [isSearchEnabled, setIsSearchEnabled] = useState<boolean>(false);

  const clickSearchHandler = () => {
    setIsSearchEnabled(!isSearchEnabled);
  };

  return (
    <section className="min-h-[calc(100vh_-_88px)] pb-[88px]">
      <Head>
        <title>{pageTitle || "Dotorimook's DevLog"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar isSearchEnabled={isSearchEnabled} onSearch={clickSearchHandler} />
      <section
        className={`${
          isSearchEnabled && "pt-[72px] sm:pt-[108px] lg:pt-36"
        } w-full`}
      >
        {children}
      </section>
      <Footer />
    </section>
  );
};

export default BaseLayout;
